---
- name: Zip all file in Depot\Archive
  win_shell: |
    $compress = @{
    Path= "E:\Work\{{ item }}\*"
    Exclude= "E:\Work\{{ item }}\Archive"
    CompressionLevel = "Fastest"
    DestinationPath = "E:\Work\{{ item }}\Archive\{{ date }}.zip" 
    }
    Compress-Archive @compress
  with_items: "{{ inputname }}"


  # (Get-ChildItem "E:\Depot\Artifactory\Inputs").Name | %{Remove-Item "E:\Work\Test\Test\$($_)" -Force -Recurse -ErrorAction Ignore}


