---
- name: Zip all file in Depot\Archive
  win_shell: |
    $YourDirToCompress="E:\Work\{{ item }}"
    $ZipFileResult="E:\Work\{{ item }}\Archive\{{ date }}.zip"
    $DirToExclude=@("*Archive*", "*archive*", "*ARCHIVE*")
    Get-ChildItem $YourDirToCompress -Directory -Exclude $DirToExclude |
    Compress-Archive -DestinationPath $ZipFileResult -Update
  with_items: "{{ inputname }}"
  # (Get-ChildItem "E:\Depot\Artifactory\Inputs").Name | 
  # %{Remove-Item "E:\Work\Test\Test\$($_)" -Force -Recurse -ErrorAction Ignore}
