[all:vars]
date="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
url_artifactory=production-services_R19.5.0.2.zip
webservice=["ConsolidationService", "ConversionService"]

[windows-server]
192.234.226.177
[windows-server:vars]
disk=E:\

[windows-sql]
192.234.226.176
[windows-sql:vars]
disk=E:\

[all:vars]
ansible_user=WinRM
ansible_password=Navblue123*
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore