[all:vars]
url_artifactory=production-services_R19.5.0.2.zip

[windows-server]
192.234.226.177

[windows-server:vars]
ansible_user=WinRM
ansible_password=Navblue123*
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore

[windows-sql]
192.234.226.176

[windows-sql:vars]
ansible_user=WinRM
ansible_password=Navblue123*
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore