[windows-server]
192.234.226.177

[windows-server:vars]
ansible_user=INT\raphael.barrocas_adm
ansible_password=N@vblue04!
ansible_port=5985
ansible_ssh_port=5985
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore





