[all:vars] #Global variable
date="{{ lookup('pipe', 'date +%Y%m%d') }}" #Date of the day
url_artifactory=production-services_R19.5.0.2.zip #Choose the file name of artifactory
webservice=["ConsolidationService", "ConversionService"] #Choose the webservices for deploy

[windows-server] #Server IP
192.234.226.177
[windows-server:vars]
disk=E:\ #Choose the disk name for deployment

[windows-sql] #Server IP
192.234.226.176
[windows-sql:vars]
disk=E:\ #Choose the disk name for deployment

[all:vars] #Host remote parameter
ansible_user=WinRM
ansible_password=Navblue123*
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore