[windows-server]
192.234.226.177

[windows-server:vars]
ansible_user=raphael.barrocas_adm
ansible_password=N@vblue04!
ansible_ssh_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore





