[windows-server]
http://webintval.navblue.aero/

[windows-server:vars]
ansible_user=raphael.barrocas_adm
ansible_password=N@vblue04!
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore


