[windows-server]
192.234.226.177

[windows-server:vars]
ansible_user=raphael.barrocas_admin@int.navblue.aero
ansible_password=N@vblue04!
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore





