---
# - hosts: windows-server
#   remote_user: root
#   vars:  
#     - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
#     - webservice:
#       - ConsolidationService
#     - url_artifactory: production-services_R19.5.0.2.zip

#   roles:
#     - role: artifactory
#     - role: archive
#     - role: update_dll
#     - role: update_webconfig
#       vars:
#         webconfig: Web.config
#         webservice:
#           - ConsolidationService

# - hosts: windows-sql
#   remote_user: root
#   vars:  
#     - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
#     - webservice:
#       - ConsolidationService
#     # - url_artifactory: production-services_R19.5.0.2.zip
#     - sql_name: ALBVAL

#   roles:
#     - role: restart_sql_server

- hosts: windows-server
  vars:  
    - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - webservice:
      - ConsolidationService
    - url_artifactory: production-services_R19.5.0.2.zip

  roles:
    - role: iisreset