---
# - hosts: windows-server
#   remote_user: root
#   vars:  
#     - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
#     - webservice:
#       - ConsolidationService
#     - url_artifactory: production-services_R19.5.0.2.zip

#   roles:
#     - role: artifactory

- hosts: windows-sql
  remote_user: root
  vars:  
    - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - webservice:
      - ConsolidationService
    - url_artifactory: production-services_R19.5.0.2.zip

  roles:
    - role: artifactory
    # - role: update_sql
