---
- hosts: windows-sql
  remote_user: root
  vars:  
    - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - webservice:
      - ConsolidationService
    - url_artifactory: production-services_R19.5.0.2.zip

  - name: Example from an Ansible Playbook
    win_ping:

#  roles:
#    - role: artifactory
#    - role: archive
#    - role: update_dll
#    - role: update_webconfig
#      vars:
#        webconfig: Web.config
#        webservice:
#          - ConsolidationService