---
- hosts: windows-server
  remote_user: root
  vars:
    - webservice:
      - ConsolidationService
      - ConversionService
    - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  roles:
    - archive
