---
- hosts: windows-server
  remote_user: root
  vars:
    - date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - chemins:
      - ConsolidationService
      - ConversionService

  roles:
    - archive
