---
- hosts: windows-server
  remote_user: root

  tasks:
    - name: test connection
      win_ping:
    - name: Create a zip archive of /path/to/foo
      archive:
        path: E:\ConsolidationService\Web.config





