---
- hosts: windows-server
  remote_user: root

  tasks:
    - name: test connection
      win_ping:
    - name: Run multi-lined shell commands
      win_shell: Compress-Archive -Path E:\ConsolidationService\Web.config -DestinationPath E:\ConsolidationService\Archive\archive.zip






