---
-name: Copier coller 
 hosts: web
 remote_user: root

 tasks:
    -name: Copier coller fichier test1
     win_copy:
     src: C:\Users\dbarthe\Desktop\Travail\TestAnsible\Ansible\SalutTest.txt
     dest: C:\inetpub\wwwroot\Test


...
