---
- hosts: windows-server
  remote_user: root
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"    
	
  tasks:
    - name: Zip Web.config file
      win_shell: |
        $compress = @{
        Path= "E:\ConsolidationService\Web.config", "E:\ConsolidationService\bin"
        CompressionLevel = "Fastest"
        DestinationPath = "E:\ConsolidationService\Archive\{{ date }}.zip"
        }
        Compress-Archive @compress
		
		
