---
- hosts: windows-server
  remote_user: root
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"

  tasks:
    - name: Test connection with windows host
      win_ping:
    - name: Zip Web.config file
      win_shell: Compress-Archive -Path E:\ConsolidationService\Web.config -DestinationPath E:\ConsolidationService\Archive\{{ date }}.zip
    - name: Zip Bin file
      win_shell: Compress-Archive -Path E:\ConsolidationService\bin -DestinationPath E:\ConsolidationService\Archive\{{ date }}.zip
   
  




