---
- hosts: windows-server
  vars:  
    - webservice:
      - ConsolidationService
      - ConversionService

  roles:
    - role: artifactory
    - role: archive
    - role: update_dll
    - role: update_webconfig
      vars:
        webconfig: Web.config
        webservice:
          - ConsolidationService
    # - role: update_input
    #   vars:
    #     inputname:
    #       - example

- hosts: windows-sql
  vars:  
    - sql_name: ALBVAL
    - file_name: 
      - Db_Qualification_to19.5.0.2

  roles:
    - role: artifactory
    - role: update_sql
    - role: restart_sql_server

- hosts: windows-server

  roles:
    - role: iisreset
    - role: test_webservice
      vars:
        url_wsdl:
          - https://localhost:4023/ConsolidationService.svc?wsdl