---
- hosts: windows-server
  remote_user: root

  tasks:
    - name: test connection
      win_ping:
    - name: zip a directory
      win_zip:
        src:  E:\ConsolidationService\Web.config
        dest:  E:\ConsolidationService\Archive\test.zip
        creates: E:\ConsolidationService\Archive\test.zip





