---
- hosts: windows-server
  remote_user: root
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"    
  with_items:
    - E:\ConsolidationService

  tasks:
    - name: test connection
      win_ping:
#Archive ConsolidationService
    - name: Copy Archive.zip in Depot1\Archive
      win_copy:
        src: "{{ item }}"\Archive.zip
        dest: E:\Depot1\Archive\Archive.zip
        remote_src: yes

    - name: Remove Archive.zip in ConsolidationService
      win_file:
        path: {{ item }}\Archive.zip
        state: absent

    - name: Unzip Archive.zip in Depot1\Archive
      win_unzip:
        src: E:\Depot1\Archive\Archive.zip
        dest: E:\Depot1\Archive\
        remote_src: yes

    - name: Zip all file in Depot1\Archive
      win_shell: |
        $compress = @{
        Path= "{{ item }}\Web.config", "{{ item }}", "{{ item }}\ConsolidationService.log"
        CompressionLevel = "Fastest"
        DestinationPath = "E:\Depot1\Archive\{{ date }}.zip"
        }
        Compress-Archive @compress
    - name: Delete Archive.zip in Depot1\Archive
      win_file:
        path: E:\Depot1\Archive\Archive.zip
        state: absent

    - name: Zip all file in Depot1\Archive
      win_shell: |
        $compress = @{
        Path= "E:\Depot1\Archive\*"
        CompressionLevel = "Fastest"
        DestinationPath = "{{ item }}\Archive.zip"
        }
        Compress-Archive @compress
    - name: Remove Depot1\Archive
      win_file:
        path: E:\Depot1\Archive
        state: absent

    - name: Create Depot1\Archive
      win_file:
        path: E:\Depot1\Archive
        state: directory
##################################
