---
- hosts: windows-server
  remote_user: root
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"    

  tasks:
    - name: test connection
      win_ping:

    - name: Copy a single file
      win_copy:
        src: E:\ConsolidationService\Archive\{{ date }}
        dest: E:\ConsolidationService\Archive.zip\{{ date }}
        remote_src: yes
