---
- hosts: windows-server
  remote_user: root
  tasks:
    - name: test connection
      win_ping:
    - name: Copy a single file where the source is on the remote host
      win_copy:
        src: E:\Test1\Test1.txt
        dest: E:\Test2\Test1.txt
        remote_src: yes
    - name: Copy a single file
      win_copy:
        src: host.yml
        dest: E:\Test2\host.yml
