---
- hosts: windows-server
  remote_user: root
  tasks:
    - name: test connection
      win_ping:
    - name: Download earthrise.jpg to specified path
      win_get_url:
        url: https://www.numerama.com/content/uploads/2019/05/trou-noir-espace-univers-astronomie.jpg
        dest: E:\Test2\trou-noir-espace-univers-astronomie.jpg




