---
- hosts: windows-server
  remote_user: root

  tasks:
    - name: test connection
      win_ping:
    - name: Create a bz2 archive of multiple files, rooted at /path
      archive:
        path: E:\ConsolidationService\Web.config
        dest: E:\ConsolidationService\Archive\test.zip
        format: zip



