---
- hosts: windows-server
  remote_user: root
  tasks:
    - name: test connection
      win_ping:
    - name: Copy a single file
      win_copy:
        src: https://artifactory.navblue.tech/artifactory/data-plus/Production-Services/production-services_R19.5.0.2.zip
        dest: E:\Test2\production-services_R19.5.0.2.zip
