---
- hosts: windows-server
  remote_user: root
  tasks:
    - name: test connection
      win_ping:

    - name: Copy a single file
      win_copy:
        src: C:\Utilisateurs\dbarthe\Documents\production-services_R19.5.0.2.zip
        dest: E:\Test2\test.zip




