---
- hosts: windows-server
  remote_user: root
  tasks:
    - name: test connection
      win_ping:
      
    - name: Download
      win_get_url:
        url: https://file-examples.com/wp-content/uploads/2017/02/zip_2MB.zip
        dest: E:\Test2\production-services_R19.5.0.2.zip




