---
- hosts: windows-server
  remote_user: root
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"    

  tasks:
    - name: test connection
      win_ping:

    - name: Archiver l'ancienne version dans le zip archive
      win_shell: |
        $compress = @{
        Path= "E:\ConsolidationService\Web.config", "E:\ConsolidationService\bin"
        CompressionLevel = "Fastest"
        DestinationPath = "E:\ConsolidationService\Archive.zip\{{ date }}.zip"
        }
        Compress-Archive @compress
