---
- name: Restart Web Service IIS
  win_iis_website:
    name: ConsolidationService
    state: restarted

- name: Test web service
  win_uri:
    url: '{{ item }}'
    validate_certs: no
    status_code: 200
  with_items: "{{ url_wsdl }}"
