---
- name: Zip all file in Depot\Archive
  win_shell: |
    $YourDirToCompress="{{ disk }}Work\{{ item }}"
    $ZipFileResult="{{ disk }}Work\{{ item }}\Archive\{{ date }}.zip"
    $DirToExclude=@("*Archive*", "*archive*", "*ARCHIVE*")
    Get-ChildItem $YourDirToCompress -Directory -Exclude $DirToExclude |
    Compress-Archive -DestinationPath $ZipFileResult -Update
  with_items: "{{ inputname }}"

- name: Delete old inputs
  win_shell: |
    (Get-ChildItem "{{ disk }}Depot\Artifactory\{{ item }}\Inputs").Name | 
    %{Remove-Item "{{ disk }}Work\{{ item }}\$($_)" -Force -Recurse -ErrorAction Ignore}
  with_items: "{{ inputname }}"

- name: Copy new inputs
  win_shell: Get-ChildItem -Path "{{ disk }}Depot\Artifactory\{{ item }}\Inputs" | Copy-Item -Destination {{ disk }}Work\{{ item }}\
  with_items: "{{ inputname }}"
