---
- name: Zip all file in Depot\Archive
  win_shell: |
    $YourDirToCompress="E:\Work\{{ item }}"
    $ZipFileResult="E:\Work\{{ item }}\Archive\{{ date }}.zip"
    $DirToExclude=@("*Archive*", "*archive*", "*ARCHIVE*")
    Get-ChildItem $YourDirToCompress -Directory -Exclude $DirToExclude |
    Compress-Archive -DestinationPath $ZipFileResult -Update
  with_items: "{{ inputname }}"

- name: Delete old inputs
  win_shell: |
    (Get-ChildItem "E:\Depot\Artifactory\{{ item }}\Inputs").Name | 
    %{Remove-Item "E:\Work\{{ item }}\$($_)" -Force -Recurse -ErrorAction Ignore}
  with_items: "{{ inputname }}"

- name: Copy new inputs
  win_shell: Get-ChildItem -Path "E:\Depot\Artifactory\{{ item }}\Inputs" | Copy-Item -Destination E:\Work\{{ item }}\
  with_items: "{{ inputname }}"
