---
- name: STOP sql server
  win_command: NET STOP {{ server_name }}
  register: result
  ignore_errors: yes

- name: Confirm ?
  win_command: Y
  when: 'result.stdout_lines == ["The following services are dependent on the SQL Server (ALBVAL) service.", "Stopping the SQL Server (ALBVAL) service will also stop these services.", "", "   SQL Server Agent (ALBVAL)", "", "Do you want to continue this operation? (Y/N) [N]: "]'

- name: START sql server
  win_command: NET START {{ server_name }}
