---
- name: Create a directory if it does not exist
  file:
    path: E:\Depot\Artifactory
    state: directory

#- name: Unzip 
#  win_unzip:
#    src: E:\Depot\Artifactory\{{ url_artifactory }}
#    dest: E:\Depot\Artifactory\
#    recurse: yes

#- name: Copy bin file
#  win_copy:
#    src: E:\Depot\{{ url_artifactory }}\Albatross_2.0_R19.5.0.2.zip\{{ webservice }}\bin\
#    dest: E:\Depot\
#    remote_src: yes
#  with_items: "{{ webservice }}"

