---
- name: Create Depot1\Archive
  win_file:
    path: E:\Depot1\Archive\{{ item }}
    state: directory
  with_items: "{{ webservice }}"

- name: Copy Archive.zip in Depot1\Archive
  win_copy:
    src: E:\{{ item }}\Archive.zip
    dest: E:\Depot1\Archive\{{ item }}\{{ item }}.zip
    remote_src: yes
  with_items: "{{ webservice }}"

- name: Remove Archive.zip in {{ item }}
  win_file:
    path: E:\{{ item }}\Archive.zip
    state: absent
  with_items: "{{ webservice }}"

- name: Unzip Archive.zip in Depot1\Archive
  win_unzip:
    src: E:\Depot1\Archive\{{ item }}\{{ item }}.zip
    dest: E:\Depot1\Archive\{{ item }}
    remote_src: yes
  with_items: "{{ webservice }}"

- name: Zip all file in Depot1\Archive
  win_shell: |
    $compress = @{
    Path= "E:\{{ item }}\Web.config", "E:\{{ item }}\bin", "E:\{{ item }}\{{ item }}.log"
    CompressionLevel = "Fastest"
    DestinationPath = "E:\Depot1\Archive\{{ item }}\{{ date }}.zip"
    }
    Compress-Archive @compress
  with_items: "{{ webservice }}"

- name: Delete Archive.zip in Depot1\Archive
  win_file:
    path: E:\Depot1\Archive\{{ item }}\{{ item }}.zip
    state: absent
  with_items: "{{ webservice }}"

- name: Zip all file in Depot1\Archive
  win_shell: |
    $compress = @{
    Path= "E:\Depot1\Archive\{{ item }}\*"
    CompressionLevel = "Fastest"
    DestinationPath = "E:\{{ item }}\Archive.zip"
    }
    Compress-Archive @compress
  with_items: "{{ webservice }}"

- name: Remove Depot1\Archive\{{ item }}
  win_file:
    path: E:\Depot1\Archive
    state: absent
  with_items: "{{ webservice }}"
