---
- name: Create Depot\Archive
  win_file:
    path: '{{ disk }}Depot\Archive\{{ item }}'
    state: directory
  with_items: "{{ webservice }}"

- name: Copy Archive.zip in Depot\Archive
  win_copy:
    src: '{{ disk }}{{ item }}\Archive.zip'
    dest: '{{ disk }}Depot\Archive\{{ item }}\{{ item }}.zip'
    remote_src: yes
  with_items: "{{ webservice }}"

- name: Remove Archive.zip in {{ item }}
  win_file:
    path: '{{ disk }}{{ item }}\Archive.zip'
    state: absent
  with_items: "{{ webservice }}"

- name: Unzip Archive.zip in Depot\Archive
  win_unzip:
    src: '{{ disk }}Depot\Archive\{{ item }}\{{ item }}.zip'
    dest: '{{ disk }}Depot\Archive\{{ item }}'
    remote_src: yes
  with_items: "{{ webservice }}"

- name: Zip all file in Depot\Archive
  win_shell: |
    $compress = @{
    Path= "{{ disk }}{{ item }}\Web.config", "{{ disk }}{{ item }}\bin", "{{ disk }}{{ item }}\{{ item }}.svc"
    CompressionLevel = "Fastest"
    DestinationPath = "{{ disk }}Depot\Archive\{{ item }}\{{ date }}.zip"
    }
    Compress-Archive @compress
  with_items: "{{ webservice }}"

- name: Delete Archive.zip in Depot\Archive
  win_file:
    path: '{{ disk }}Depot\Archive\{{ item }}\{{ item }}.zip'
    state: absent
  with_items: "{{ webservice }}"

- name: Zip all file in Depot\Archive
  win_shell: |
    $compress = @{
    Path= "{{ disk }}Depot\Archive\{{ item }}\*"
    CompressionLevel = "Fastest"
    DestinationPath = "{{ disk }}{{ item }}\Archive.zip"
    }
    Compress-Archive @compress
  with_items: "{{ webservice }}"

- name: Remove Depot\Archive
  win_file:
    path: '{{ disk }}Depot\Archive'
    state: absent
