---
- name: Download artifactory on local
  get_url: url=https://artifactory.navblue.tech/artifactory/data-plus/Production-Services/{{ url_artifactory }} dest=depot/
  delegate_to: localhost

- name: Copy file and paste on remote host
  win_copy:
    src: depot/{{ url_artifactory }}
    dest: E:\Depot\

- name: Remove file in depot local
  file: path=depot/{{ url_artifactory }} state=absent
  delegate_to: localhost
