---
- name: Download foo.conf
  win_get_url:
    url: https://artifactory.navblue.tech/artifactory/data-plus/Production-Services/production-services_R19.5.0.2.zip
    dest: C:\Test\
    delegate_to: 127.0.0.1
