---
- name: Delete directory Depot
  win_file:
    path: "{{ disk }}Depot"
    state: absent

- name: Create directory Depot
  win_file:
    path: "{{ disk }}Depot"
    state: directory

- name: Delete directory Artifactory
  win_file:
    path: "{{ disk }}"Depot\Artifactory
    state: absent

- name: Create directory Artifactory
  win_file:
    path: "{{ disk }}Depot\Artifactory"
    state: directory

- name: Download artifactory on local
  get_url: url=https://artifactory.navblue.tech/artifactory/data-plus/Production-Services/{{ url_artifactory }} dest=depot/
  delegate_to: localhost

- name: Copy file and paste on remote host
  win_copy:
    src: depot/{{ url_artifactory }}
    dest: "{{ disk }}Depot\Artifactory\ "

- name: Remove file in depot local
  file: path=depot/{{ url_artifactory }} state=absent
  delegate_to: localhost

- name: Unzip Artifactory
  win_unzip:
    src: "{{ disk }}Depot\Artifactory\{{ url_artifactory }}"
    dest: "{{ disk }}Depot\Artifactory\ "
    recurse: yes